### ISSUE TITLE
在查询标的实时行情 接口封装的时候 弄错接口了

### ISSUE THREAD

**Issue by iFrankWu** [vnpy/vnpy_xtp#11]
https://github.com/vnpy/vnpy_xtp/blob/d64dcd2f3c04e99907c50bf3b825ea8dc1663086/vnpy_xtp/api/vnxtp/vnxtpmd/vnxtpmd.cpp#L687

在查询标的实时行情 接口封装的时候 弄错接口了

正常的接口应该是QueryTickersPriceInfo

<img width="1390" alt="image" src="https://github.com/vnpy/vnpy_xtp/assets/6120669/7013c1b4-a901-4eeb-b326-128cb8c18d53">

**Comment by vnpy** [comment]
感谢反馈，我们来修复下

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_xtp/pull/12
